server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fm
    username: fm
    password: fm
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    baseline-on-migrate: true